spring:
  application:
    name: hello-spring-boot
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/?useSSL=false&serverTimezone=UTC
    username: 
    password: 
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.baize.hello.spring.boot.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8088
  servlet:
    context-path: /boot

logging:
  file: ../logs/spring-boot-hello.log
  level.org.springframework.web: DEBUG
